### PR TITLE
l10n: translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [ubuntu-desktop-installer/ubuntu-bootstrap](https://hosted.weblate.org/projects/ubuntu-desktop-installer/ubuntu-bootstrap/).

It also includes following components:

* [ubuntu-desktop-installer/ubuntu-provision](https://hosted.weblate.org/projects/ubuntu-desktop-installer/ubuntu-provision/)

* [ubuntu-desktop-installer/ubuntu-init](https://hosted.weblate.org/projects/ubuntu-desktop-installer/ubuntu-init/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by xSAVIKx** [comment]
@d-loose, how come you approved this?

**Comment by sdwvit** [comment]
Human error probably

**Comment by rimmer** [comment]
Just a comment from the native speaker (me): the phrases used aren't fully correct in a way that no native speaker would say like that. 
Seems like a Russian trace. 
Watch out!

**Comment by rimmer** [comment]
> @d-loose, how come you approved this?

I guess there is no reason to blame the approver, this comes from Weblate, and the community there is responsible for letting this happen

**Comment by tim-hm** [comment]
Locking this conversation as its off topic now.

**Pull request merged**
