### PR TITLE
fix: Fetch file images from whitelabel directory

### PR DESCRIPTION
**Pull request by spydon**
All images should be fetched from `/usr/share/desktop-provision/images` so that the users doesn't have to specify the full path (and since we anyways can't support any path.

### CODE REVIEW

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Comment by d-loose** [comment]
@spydon something I overlooked here: the file image paths are still expected to be 'absolute' (now within the `/usr/share/desktop-provision/images` directory). So a valid config entry would look like
```yaml
pages:
  locale:
    image: "/myimage.png"
```
That `/` shouldn't be necessary.

**Comment by spydon** [comment]
@d-loose it looks like that shouldn't be needed from this (hard to link lines from the GitHub app):
```
final imagePath = '${ConfigService.whiteLabelDirectory}images/$imageName';
```
But I guess you tried? Some other place that overlooks it?

**Comment by d-loose** [comment]
There's
```dart
...
} else if (isAbsolutPath) {
  loadFutures.add(_loadFile(imageConfig, pageName, context));
...
```
in `preCache`

**Comment by spydon** [comment]
> There's
> ```dart
> ...
> } else if (isAbsolutPath) {
>   loadFutures.add(_loadFile(imageConfig, pageName, context));
> ...
> ```
> in `preCache`

Aaah let's remove it!

**Pull request merged**
