### PR TITLE
fix: typo in shown command to retrieve recovery key (#2282)

### PR DESCRIPTION
**Pull request by jpnurmi**
Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>
(cherry picked from ubuntu_desktop_installer commit f4c79e57d47acec293ea7d70e78438eb080434b6)

/cc @ogayot

### CODE REVIEW

**Review by d-loose — APPROVED** [review]
LGTM :+1:

**Comment by jpnurmi** [comment]
@ogayot i noticed you've been using (at)canonical.com address for the commits in subiquity. was https://github.com/canonical/ubuntu-desktop-installer/pull/2282 done through the web UI?

**Comment by jpnurmi** [comment]
I thought I'd cherry-pick the change for you instead of asking you to cherry-pick it into another repo but I didn't anticipate the CLA check failing. Would you mind if I amended the commit author to use your Canonical address to make the bot happy?

**Comment by ogayot** [comment]
> I thought I'd cherry-pick the change for you instead of asking you to cherry-pick it into another repo but I didn't anticipate the CLA check failing. Would you mind if I amended the commit author to use your Canonical address to make the bot happy?

Sure, please do. The original commit in ubuntu-desktop-installer was using my [at]canonical.com address so I'm not sure why it's using a personal address here.

> i noticed you've been using (at)canonical.com address for the commits in subiquity. was https://github.com/canonical/ubuntu-desktop-installer/pull/2282 done through the web UI?

Nope, I pushed it from my local ubuntu-desktop-installer tree.

**Pull request merged**
