### PR TITLE
fix: Always format root partition

### PR DESCRIPTION
**Pull request by spydon**
This forces the partition that is chosen as root to be formatted.

### CODE REVIEW

**Review by BLKKKBVSIK — APPROVED** [review]

**Comment by d-loose** [comment]
@spydon I suppose this is related to https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2058638?
It seems like I can still leave the root partition unformatted though

[Screencast from 2024-04-02 15-39-10.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/113362648/fa745a77-5533-405b-a6b8-e246b1f2adfc)

**Comment by spydon** [comment]
> @spydon I suppose this is related to https://bugs.launchpad.net/ubuntu-desktop-provision/+bug/2058638?
> It seems like I can still leave the root partition unformatted though
> 
> [Screencast from 2024-04-02 15-39-10.webm](https://github.com/canonical/ubuntu-desktop-provision/assets/113362648/fa745a77-5533-405b-a6b8-e246b1f2adfc)
> 

Aah, indeed, didn't think about that the user obviously can change back to the previous option. 🤦‍♂️

**Comment by spydon** [comment]
@d-loose fix here: https://github.com/canonical/ubuntu-desktop-provision/pull/580

**Comment by lovasoa** [comment]
Hello ! Is there a plan to re-allow installing without formatting ?

**Comment by spydon** [comment]
> Hello ! Is there a plan to re-allow installing without formatting ?

Since it can lead to all kinds of weird behavior I don't think there is any plan on allowing that again.
If there are things you would like to keep between installations I would recommend putting them on another partition that you can set the mount point for in the advanced partitioning page in the installer, or if it is a previous Ubuntu installation, upgrade instead of doing a re-installation.

**Comment by lovasoa** [comment]
This had been supported for years, and it still documented all over the web. For instance: https://help.ubuntu.com/community/UbuntuReinstallation

Maybe such a feature removal could be discussed with the community ?

**Comment by spydon** [comment]
> This had been supported for years, and it still documented all over the web. For instance: https://help.ubuntu.com/community/UbuntuReinstallation
> 
> Maybe such a feature removal could be discussed with the community ?

Thanks for the info, I'll check with the team on Monday. It might be something that the subiquity team needs to solve before it can be enabled in the UI.

**Comment by spydon** [comment]
@lovasoa I had a chat with the team and this is indeed something that subiquity has to implement, they said they were going to put it on the roadmap, but it's not there yet.

**Comment by lovasoa** [comment]
Thanks for following up. Let's hope it can be implemented soon!

**Pull request merged**
