### PR TITLE
chore: re-integrate subiquity_client

### PR DESCRIPTION
**Pull request by d-loose**
* Removes the subiquity_client submodule
* (re-)imports subiquity_client and subiquity_test into the repo
* Includes subiquity as a submodule for subiquity_client (we don't have a better solution for this now, since we're generating the dart classes for the subiquity types automatically from subiquity's source)
* Includes subiquity_client and subiquity_test in the CI (essentially reverts https://github.com/canonical/ubuntu-desktop-provision/pull/34 and https://github.com/canonical/ubuntu-desktop-installer/pull/1971). We can think about optimizing the CI and running jobs in parallel after including the new backend.

### CODE REVIEW

**Review by matthew-hagemann — CHANGES_REQUESTED** [review]
Hi Dennis :slightly_smiling_face: I am battling to get the tests passing locally for the package `subiquity_client`. I am getting timeout errors:

```
00:32 +9 -1: /home/ubuntu/dev/ubuntu-desktop-provision/packages/subiquity_client/test/subiquity_client_test.dart: wait ready                                                       00:32 +9 -1: /home/ubuntu/dev/ubuntu-desktop-provision/packages/subiquity_client/test/subiquity_client_test.dart: wait ready [E]                                                                       
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts
  dart:isolate  _RawReceivePort._handleMessage
```
 To make compare, I pulled the original client and built/tested it without any issue:
```
 00:13 +82: All tests passed!                                                                                                                                                                           
subiquity_client: SUCCESS
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
subiquity_test:
```

I created a multipass VM for testing and installed everything fresh:
- `make install_deps` and `make check` on subiquity
- `dart run build_runner build --delete-conflicting-outputs` within the client 
- `melos test` at the project root

It could very well be I am just missing a dependency for the new setup. I think a `README.md `on how to setup the `subiquity` sub module with its dependencies and how to run these tests for the `subiquity_client` at a package level would be a good idea :smile:

**Comment by d-loose** [comment]
Thanks for checking - it might be that I just happen to have all the required dependencies on my system already from messing with those repos in the past. I'll try to run the tests in a clean environment and check what's missing.

**Comment by d-loose** [comment]
I got it to work without any issues in a clean lxd container, so I guess it's just a documentation issue (the CI passes as well).

> I created a multipass VM for testing and installed everything fresh:
> 
>     * `make install_deps` and `make check` on subiquity
> 
>     * `dart run build_runner build --delete-conflicting-outputs` within the client
> 
>     * `melos test` at the project root

You shouldn't have to run any commands at the individual package level at all. Since all generated files are checked into the repo the build_runner only needs to be invoked (preferably through `melos generate` if any mocks or freezed classes are changed or added.
After setting up flutter (including the linux toolchain) and melos it should be enough to run:

```
melos bootstrap
make install_deps
melos test
```

Sorry for providing unclear instructions - I'll update the CONTRIBUTING.md accordingly!

**Comment by d-loose** [comment]
@matthew-hagemann I've opened a separate PR for the contribution guidelines: #182

**Comment by matthew-hagemann** [comment]
@d-loose Perfect, I'll head there now :slightly_smiling_face:

**Review by matthew-hagemann — APPROVED** [review]
All working from fresh for me! Ty for the updated guide :smile:

**Pull request merged**
