### PR TITLE
feat: Transfer factory_reset_tools to monorepo

### PR DESCRIPTION
**Pull request by spydon**
This moves over the [factory_reset_tools](https://github.com/canonical/factory-reset-tools) project to the monorepo and makes it adhere to the standards set for the monorepo.

A branch also needs to be created for the snap directory.

### CODE REVIEW

**Comment by spydon** [comment]
@medicalwei could you review this?

**Comment by medicalwei** [comment]
Since I'm not from Desktop Team I don't have permission to review this. I'll check whether I can build from it first.

**Comment by spydon** [comment]
> Since I'm not from Desktop Team I don't have permission to review this. I'll check whether I can build from it first.

I just mean to check so that everything looks alright. :)
Melos is used in this repository, so in order to run it you have to install melos first and then run `bootstrap`:
```
dart pub global activate melos
melos bootstrap
```

**Comment by medicalwei** [comment]
Okay, so factory_reset_tools is managed by melos now, so it can run some common commands across packages. To run a single project I need to go under the packages and run `flutter run`, is that how it supposed to work?

**Comment by spydon** [comment]
> Okay, so factory_reset_tools is managed by melos now, so it can run some common commands across packages. To run a single project I need to go under the packages and run `flutter run`, is that how it supposed to work?

If you're within an IDE it should recognize it as a project and you'll be able to run it directly from there, but yes, you can go into the directory and run it manually too.
I can also add a melos command to run it if it from any directory within the project if you want, so that it'd just be `melos factory_reset_tools`.

**Comment by medicalwei** [comment]
I am using an IDE (Visual Studio Code) when developing it, but I'll follow your conventions.

LGTM (though I don't have actual approval)

**Review by BLKKKBVSIK — APPROVED** [review]

**Comment by medicalwei** [comment]
I just found that snapcraft definition is not part of the transfer as the reviewer @alexmurray pointed out:
https://forum.snapcraft.io/t/manual-review-autoconnect-request-for-factory-reset-tools/39404

Would you also transfer it later?

**Comment by spydon** [comment]
> I just found that snapcraft definition is not part of the transfer as the reviewer @alexmurray pointed out:
> https://forum.snapcraft.io/t/manual-review-autoconnect-request-for-factory-reset-tools/39404
> 
> Would you also transfer it later?

Yup, like written in the PR description that needs to go in a separate branch since it unfortunately has to be in the root directory.
I'll fix that today.

**Pull request merged**
