### PR TITLE
provd: Removing pro and chown services (sprovd)

### PR DESCRIPTION
**Pull request by matthew-hagemann**
This change drops `sprovd` for security concerns. With it I have removed the `chown` and `pro` services that relied on it from the go backend, and the `chown` service from the Flutter frontend.

- The `chown` work will be made redundant by future `systemd` work for provd
- The `pro` backend will be moved to stage 5 / Flutter in the future.

While this does temporary pose an issue for the a11y and pro flutter pages, we can disable them thanks to #777 for the time being.

Closes Udeng 3455

### CODE REVIEW

**Comment by spydon** [comment]
Now this is just a draft, but the PR titles should be a bit more explanatory I think :smile:

**Review by d-loose — COMMENTED** [review]
As this renders the ubuntu pro page in ubuntu init non-functional, should we also remove the UI and service for that?

**Comment by matthew-hagemann** [comment]
> As this renders the ubuntu pro page in ubuntu init non-functional, should we also remove the UI and service for that?

We do ultimately want to write a dart backend for pro and keep the page. My thinking was to just leave it for now until we get back to that, as it can be disabled, and only the core desktop team is using it? I'm happy to remove more than I have though if you think that would be better.

**Review by d-loose — APPROVED** [review]
I see, that's fine with me then :)

**Pull request merged**
