### PR TITLE
feat: Simplify directory paths for whitelabel config file

### PR DESCRIPTION
**Pull request by spydon**
Now only looks for the config file in `/usr/share/desktop-provision/whitelabel.{yaml,yml}` and no longer takes in a custom config file as a command line argument.

### CODE REVIEW

**Comment by d-loose** [comment]
Would it be terrible to keep the `--config` argument? It's very useful for testing.

**Comment by d-loose** [comment]
> Would it be terrible to keep the `--config` argument? It's very useful for testing.

Agreed to remove it for the following reasons:
- Not needed outside of manual testing
- Incompatible with strictly confined ubuntu-init snap
- Simplification

**Review by d-loose — APPROVED** [review]
Thanks, LGTM :+1:
Do you plan to update the README in a separate PR, once all config file related changes are in?

**Comment by spydon** [comment]
> Thanks, LGTM 👍 Do you plan to update the README in a separate PR, once all config file related changes are in?

Yessss

**Pull request merged**
