### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eeickmeyer**
Apparently this doesn't work unless it's the American spelling. Tried this using `flavour` vs `flavor` and `flavor` won every time.

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Haha aah, this was mixed up in the other document previously too.

**Comment by eeickmeyer** [comment]
I considered calling the branch `provision-american-revolution` or `provision-american-rebellion`. :joy:

**Comment by eeickmeyer** [comment]
Let me see what I can do. I was only just added on Launchpad to the CLA so that might fix it, so let's see what happens when I fix the email.

**Comment by spydon** [comment]
Super, thanks!

**Pull request merged**
