### PR TITLE
fix: remove insulting l10n strings

### PR DESCRIPTION
**Pull request by d-loose**

### CODE REVIEW

**Review by kenvandine — APPROVED** [review]

**Comment by d-loose** [comment]
Sorry - amended the commit to update the generated l10n files

**Comment by C0rn3j** [comment]
When the localizations are fixed, it'd be good to add them back as `ua`, as `uk` is for United Kingdom, `ua` is for Ukraine.

**Comment by AlyoshaVasilieva** [comment]
ISO 639-1 language code for Ukrainian is `uk`, ISO 3166-1 alpha-2 country code for Ukraine is `ua`. United Kingdom is `gb`

**Comment by NazarTopolskyVilmate** [comment]
Why is removing Ukrainian localization entirely over vandalism a go to choice?

**Comment by esolitos** [comment]
@NazarTopolskyVilmate I would assume that this is just a quick fix for the current vandalism issue, and the support will be re-introduced when a proper l10n is in place. 😄

**Comment by d-loose** [comment]
We're checking translations for other languages as well and will of course restore the Ukrainian translations before the re-release!

**Comment by d-loose** [comment]
We're checking translations for other languages as well and will of course restore the Ukrainian translations before the re-release!

**Pull request merged**
