### PR TITLE
docs: Add instructions on how to report security issues

### PR DESCRIPTION
**Pull request by seb128**
Quoting SEC0026 - SSDLC

> SECURITY.md (V1.1)
> Any public repository must also include a SECURITY.md file in the root directory, which educates users/contributors on
> how to report a security concern.

The content of the file is based on the template referenced in the spec and what other Canonical repository are already using

### CODE REVIEW

**Comment by seb128** [comment]
I've changed my commit email to my canonical one to please the CLA checker, signed the commit and force pushed now

**Review by spydon — COMMENTED** [review]
Just one nit, we have a max line length of 100 for markdown files (which we really should enforce in the pipeline at some point...).

**Comment by seb128** [comment]
> Just one nit, we have a max line length of 100 for markdown files (which we really should enforce in the pipeline at some point...).

Thanks, I wrapped and forced pushed again

**Review by spydon — APPROVED** [review]
Lgtm!

**Pull request merged**
