### PR TITLE
Stage the gobject introspection packages needed for ubuntu-bug

### PR DESCRIPTION
**Pull request by seb128**
Seems to be working but the subiquity log has restricted rights so sudo is needed for that work as expected...

### CODE REVIEW

**Review by spydon — APPROVED** [review]

**Comment by d-loose** [comment]
@seb128 could you target the `main` branch? The snapcraft.yaml for the installer is located in [`ci/snap/bootstrap`](https://github.com/canonical/ubuntu-desktop-provision/tree/4675299a3f7fb174164aaaadb0e34d0e2ca2156b/ci/snap/bootstrap).

I promise we'll have a better branch setup soon!

**Comment by seb128** [comment]
I've rebased on main, force pushed and updated the target. Sorry for getting that detail wrong again!

**Comment by d-loose** [comment]
Thanks, no worries at all - we need to clean up this chaos :)

**Comment by d-loose** [comment]
@seb128 to bother you once more - could you sign your commit? :D

**Comment by seb128** [comment]
signed, got a nice 'verified' tag now ;-)

**Pull request merged**
